<script lang="ts">
	import '../../../../app.css';
	import type { PageData } from './$types.js';
	import type { CircadianPlan, DayPlan, TimeWindow } from '$lib/circadian.js';

	export let data: PageData;

	const itin = data.itinerary;
	const legs: { title: string; plan: CircadianPlan }[] = [
		{ title: `Outbound · ${itin.outbound.departureLabel} → ${itin.outbound.arrivalLabel}`, plan: itin.outbound }
	];
	if (itin.return) {
		legs.push({ title: `Return · ${itin.return.departureLabel} → ${itin.return.arrivalLabel}`, plan: itin.return });
	}

	function hhmm(m: number): string {
		const t = ((m % 1440) + 1440) % 1440;
		return `${String(Math.floor(t / 60)).padStart(2, '0')}:${String(Math.round(t % 60)).padStart(2, '0')}`;
	}
	function span(w: TimeWindow | null): string {
		return w ? `${hhmm(w.startMinutes)} – ${hhmm(w.endMinutes)}` : '—';
	}
	function rows(day: DayPlan): [string, string][] {
		const r: [string, string][] = [];
		r.push(['😴 Sleep', span(day.sleep)]);
		for (const w of day.light_seek) r.push(['☀️ Seek bright light', span(w)]);
		for (const w of day.light_avoid) r.push(['🕶️ Avoid bright light', span(w)]);
		if (day.caffeine_stop) r.push(['🚫 Caffeine cutoff', span(day.caffeine_stop)]);
		if (day.melatonin) r.push(['💊 Melatonin 0.5 mg', span(day.melatonin)]);
		return r;
	}
</script>

<svelte:head>
	<title>Printable plan — JetShift</title>
</svelte:head>

<div class="print-page min-h-screen bg-white text-slate-900">
	<div class="max-w-3xl mx-auto px-6 py-8">
		<!-- Screen-only toolbar -->
		<div class="print:hidden flex items-center justify-between gap-3 mb-6 rounded-xl bg-slate-100 border border-slate-200 px-4 py-3">
			<a href="/plan/{data.id}" class="text-sm font-medium text-indigo-700 hover:underline">← Back to plan</a>
			<button
				type="button"
				on:click={() => window.print()}
				class="rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-semibold px-4 py-2 min-h-[40px]"
			>
				🖨️ Print / Save as PDF
			</button>
		</div>

		<header class="mb-6 border-b-2 border-slate-900 pb-4">
			<h1 class="text-2xl font-extrabold tracking-tight">
				JetShift · {itin.outbound.departureLabel} → {itin.outbound.arrivalLabel}{itin.roundTrip ? ' (round trip)' : ''}
			</h1>
			<p class="text-sm text-slate-600 mt-1">
				Departing {new Date(data.departureDatetime).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}
				{#if data.flightNumber}· Flight {data.flightNumber}{/if}
				· Strategy: phase {itin.outbound.mode} of {Math.abs(itin.outbound.shiftHours).toFixed(1)}h
			</p>
		</header>

		{#each legs as leg}
			<section class="mb-8">
				<h2 class="text-lg font-bold mb-3 bg-slate-900 text-white px-3 py-1.5 rounded print:rounded-none">{leg.title}</h2>
				<div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
					{#each leg.plan.days as day}
						<div class="border border-slate-300 rounded-lg overflow-hidden break-inside-avoid">
							<div class="bg-slate-100 px-3 py-1.5 flex items-baseline justify-between border-b border-slate-300">
								<span class="font-bold text-sm">{day.label}</span>
								<span class="text-xs text-slate-600">{day.date} · {day.tzLabel} time</span>
							</div>
							<table class="w-full text-sm">
								<tbody>
									{#each rows(day) as [what, when]}
										<tr class="border-b border-slate-200 last:border-0">
											<td class="px-3 py-1">{what}</td>
											<td class="px-3 py-1 text-right font-mono whitespace-nowrap">{when}</td>
										</tr>
									{/each}
								</tbody>
							</table>
						</div>
					{/each}
				</div>
			</section>
		{/each}

		<footer class="text-xs text-slate-500 border-t border-slate-300 pt-3">
			Follow each day in the timezone shown on its card. Not medical advice — consult a physician
			before using melatonin. Generated by JetShift.
		</footer>
	</div>
</div>

<style>
	@media print {
		.print-page {
			font-size: 12px;
		}
	}
</style>
